baseURL = "www.example.com"
languageCode = "en-us"
theme = "hugo-serif-theme"
themesDir = "../.."
title = "Hugo Serif Theme"
[[menu.footer]]
name = "联系我们"
url = "/contact/"
weight = 2
[[menu.footer]]
name = "友情单位"
url = "https://www.cmu.edu/ini/admissions/request-form.html?utm_source=google&utm_medium=ad&utm_campaign=lead_form_submission&utm_id=lfs&gclid=EAIaIQobChMIjZ3Bmqeh9AIVQbaWCh0QFAf9EAAYASAAEgJHYPD_BwE"
weight = 1
[[menu.main]]
name = "联系方式"
url = "/contact/"
weight = 4
[[menu.main]]
name = "教育项目"
url = "/about/"
weight = 3
[[menu.main]]
name = "师资力量"
url = "/team/"
weight = 2
[[menu.main]]
name = "机构简介"
url = "/services/"
weight = 1
[module.hugoVersion]
extended = true
min = "0.55.0"
[params]
google_analytics_id = ""
google_tag_manager_id = ""
[params.footer]
copyright_text = "中科院哲学所版权所有2020-2021"
[params.homepage]
show_contact_box = true
show_services_button = true
[params.logo]
alt = "Serif - A Hugo Business Theme"
desktop = "images/logo/caslogo.jpg"
desktop_height = "36px"
mobile = "images/logo/logo-mobile.svg"
mobile_height = "36px"
[params.seo]
meta_twitter_creator = "@zerostaticio"
meta_twitter_site = "@zerostaticio"
[params.team]
summary_large_truncate = 120
